### PR TITLE
Logo for GeoArrow?

### PR DESCRIPTION
**Pull request by paleolimbot**
Just an idea...might be nice to have a working logo! I don't pretend that this is a work of art or anything, just what we used for the Data Thread talk a little while ago. Suggestions or alternatives welcome!

geoarrow-hex

...or the spinning version:

https://user-images.githubusercontent.com/10995762/194408261-ed354994-14ae-4cda-a4d9-6a9fb1befb3d.mp4

### CODE REVIEW

**Comment by kylebarron** [comment]
the hex... I can tell you're an R developer 😉

**Comment by martinfleis** [comment]
I would try to keep in mind that a logo needs to work at super small sizes. Imagine you have it in a corner of your presentation and there's bad connection, so your nice sharp Retina display comes across are 480p. In that case, neither "GEO" nor the outline of continents is readable. Just sharing some thoughts we had when we worked on the geopandas logo.

**Comment by kylebarron** [comment]
image
I do have to agree that that's not very readable

**Comment by kylebarron** [comment]
Might want to double check with apache that we're allowed to use the arrow logo that way? https://github.com/opengeospatial/geoparquet/pull/48#issuecomment-1079375543

**Comment by martinfleis** [comment]
I like it

**Pull request merged**
